baseURL = "https://supatagsschau.jwais.com/"
languageCode = "zh-tw"
title = "每日德語"
theme = "PaperMod"
paginate = 10

[params]
  env = "production"
  description = "每天擷取 tagesschau 20 Uhr 新聞 Podcast<br>為中文新聞閱讀與德文學習"
  author = "每日德語"
  images = ["/fh_feature.jpg"]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowShareButtons = false
  ShowCodeCopyButtons = false
  disableSpecial1stPost = true

  [params.profileMode]
    enabled = true
    title = "每日德語"
    subtitle = "每天擷取 tagesschau 20 Uhr 新聞 Podcast<br>為中文新聞閱讀與德文學習"

    [[params.profileMode.buttons]]
      name = "📰 所有文章"
      url = "/archives/"
    [[params.profileMode.buttons]]
      name = "🏷️ 主題標籤"
      url = "/tags/"

  [[params.socialIcons]]
    name = "rss"
    url = "/index.xml"

[taxonomies]
  tag = "tags"
  level = "levels"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
  name = "首頁"
  url = "/"
  weight = 1

[[menu.main]]
  name = "標籤"
  url = "/tags/"
  weight = 2
